apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-08-27T11:54:42Z"
  labels:
    app: nimbus
  name: nimbus
  namespace: default
  resourceVersion: "8205313"
  selfLink: /api/v1/namespaces/default/services/nimbus
  uid: 74a8e9bf-c8c1-11e9-a084-7e00950d7170
spec:
  clusterIP: None
  ports:
  - name: client
    port: 6627
    protocol: TCP
    targetPort: 6627
  selector:
    app: nimbus
  sessionAffinity: None
  type: ClusterIP

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: "2019-08-28T04:38:22Z"
  generation: 1
  name: nimbus
  namespace: default
  resourceVersion: "8299848"
  selfLink: /apis/apps/v1/namespaces/default/statefulsets/nimbus
  uid: aa987f0a-c94d-11e9-a084-7e00950d7170
spec:
  podManagementPolicy: OrderedReady
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nimbus
  serviceName: nimbus
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nimbus
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - nimbus
            topologyKey: kubernetes.io/hostname
      containers:
      - args:
        - storm
        - nimbus
        image: siddharthjoshi/storm:v4
        imagePullPolicy: Always
        name: kubernetes-stormnimbus
        ports:
        - containerPort: 6627
          name: client
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /apache-storm-1.2.3/extlib
          name: extlib
        - mountPath: /topology
          name: topology
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: extlib
    spec:
      accessModes:
      - ReadWriteOnce
      dataSource: null
      resources:
        requests:
          storage: 1Gi
      volumeMode: Filesystem
    status:
      phase: Pending
  - metadata:
      creationTimestamp: null
      name: topology
    spec:
      accessModes:
      - ReadWriteOnce
      dataSource: null
      resources:
        requests:
          storage: 1Gi
      volumeMode: Filesystem
    status:
      phase: Pending